### ISSUE TITLE
playwright stuck inside context for edge browser when headless=False

### ISSUE THREAD

**Issue by Dibakarroy1997** [microsoft/playwright-python#514]
I am using poetry v1.8.0a1 and trying to use edge browser v88.0.705.68 (Official Build) (64-bit)
For some reason, it does not come out of **_with_** statement:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(
        executable_path=r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe", headless=False
    )
    page = browser.new_page()
    page.goto("http://www.google.com/")
    browser.close()
```

![image](https://user-images.githubusercontent.com/17507690/108299222-0963db80-71c4-11eb-9b48-c5355068336c.png)

I had to press **control+C** to come out of the context which again throws an exception:

```python
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\windows-automation-kits-RkQ0kSwR-py3.8\lib\site-packages\playwright\sync_api\_generated.py", line 10012, in close
    result = mapping.from_maybe_impl(self._sync(self._impl_obj.close()))
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\windows-automation-kits-RkQ0kSwR-py3.8\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    self._dispatcher_fiber.switch()
  File "C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\windows-automation-kits-RkQ0kSwR-py3.8\lib\site-packages\playwright\sync_api\_context_manager.py", line 48, in greenlet_main
    loop.run_until_complete(self._connection.run_as_sync())
  File "c:\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\python38\lib\asyncio\base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "c:\python38\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
  File "c:\python38\lib\asyncio\windows_events.py", line 779, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt
```

Can we seen in interactive mode also:

```python
>>> from playwright.sync_api import sync_playwright
>>> playwright = sync_playwright().start()
>>> browser = playwright.chromium.launch(executable_path=r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe", headless=False)
>>> page = browser.new_page()
>>> page.goto("http://whatsmyuseragent.org/")
<playwright.sync_api._generated.Response object at 0x0000020489B9DA60>
>>> browser.close()
```

![image](https://user-images.githubusercontent.com/17507690/108302044-34046300-71c9-11eb-8b46-3c4cc5d8a1ea.png)

**Comment by mxschmitt** [comment]
@Dibakarroy1997 

This should be fixed in the latest version by using channels and Playwright gets now tested on Microsoft Edge stable.

See here for channels: https://playwright.dev/python/docs/api/class-browsertype#browser_typelaunchkwargs

and instead of using the context manager, which is designed to close the browser once the context is excited, you can use the methods available for REPL usage: https://github.com/microsoft/playwright-python#interactive-mode-repl

**Comment by Dibakarroy1997** [comment]
Hi @mxschmitt,

I am using playwright v1.10.0

Running in REPL. Although it is closing the browser, the interactive terminal is still blocked. It does not release it until I manually press `Ctrl + C`

![image](https://user-images.githubusercontent.com/17507690/113499744-fc156d00-9535-11eb-89f3-46606432463b.png)

![image](https://user-images.githubusercontent.com/17507690/113499763-249d6700-9536-11eb-9c85-51c6abb23396.png)

This is the edge version I am using:

**Microsoft Edge** | 89.0.774.68 (Official build) (64-bit)
**Revision** | 539ddb33b714f303e253891a6c693bf2798d0daa


![image](https://user-images.githubusercontent.com/17507690/113499826-b907c980-9536-11eb-8670-2670fe831486.png)

**Comment by kumaraditya303** [comment]
I am unable to reproduce the behaviour, Can you try it with latest `msedge` that is:


Microsoft Edge | 90.0.818.41 (Official build) (64-bit)
-- | --
Revision | 8c973b4394f22bf1257b81a2d9021393858aecb2


@Dibakarroy1997

**Comment by Dibakarroy1997** [comment]
@kumaraditya303 I am still seeing the same issue even after upgrading the edge to 90.0.818.41. Are you using async API or sync API?

**Comment by kumaraditya303** [comment]
@Dibakarroy1997 I am using sync API

**Comment by mxschmitt** [comment]
I also tried to reproduce and can't. Using Windows, Edge, same code as shown. Closing for now.
